# Generated by Django 3.0.7 on 2020-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ques',
            field=models.CharField(max_length=500),
        ),
    ]
